### ISSUE TITLE
Ajenti error

### ISSUE THREAD

**Issue by bear330** [cubieplayer/Cubian#224]
Hi, 

I cannot connect to my cubian's reinstalled Ajenti, I didn't do anything, almost new cubian, here is my /var/log/ajenti.err.log:

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/gevent/greenlet.py", line 390, in run
    result = self._run(_self.args, *_self.kwargs)
  File "/usr/lib/pymodules/python2.7/gevent/server.py", line 159, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/usr/lib/pymodules/python2.7/gevent/ssl.py", line 419, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/pymodules/python2.7/gevent/ssl.py", line 84, in __init__
    cert_reqs, ssl_version, ca_certs)
SSLError: _ssl.c:298: Both the key & certificate files must be specified for server-side operation
<Greenlet at 0xf2f800: <bound method SocketIOServer.wrap_socket_and_handle of <SocketIOServer at 0xf08d10 fileno=6 address=0.0.0.0:8000>>(<socket at 0x1316470 fileno=15 sock=127.0.0.1:8000, ('127.0.0.1', 35556))> failed with SSLError

I tried ajenti-ssl-gen, it told me everything is OK.

How can I solve this problem? Thanks.

**Comment by michalliu** [comment]
It seems your ajenti private key has corrupted. You may try to fix the problem with

> /usr/bin/ajenti-ssl-gen `/bin/hostname` -f
